Repository fake-useragent/fake-useragent, pull requests merged in 2024-12, with the labels that each got.

#400 Using the new JSONlines format + new data source
  .gitignore
  README.md
  pyproject.toml
  src/fake_useragent/__init__.py
  src/fake_useragent/data/browsers.json
  src/fake_useragent/data/browsers.jsonl
  src/fake_useragent/fake.py
  src/fake_useragent/get_version.py
  src/fake_useragent/settings.py
  src/fake_useragent/utils.py
  tests/__init__.py
  tests/test_fake.py
  tests/test_utils.py
  ua-converter/ua_convert.py
Labels: bug, enhancement, urgent, ua-file

#415 Update README.md
  README.md
Labels: documentation

#422 Trigger only once per month
  .github/workflows/update_bundled_useragents.yml
Labels: enhancement

#424 Speedup `ua_convert` parser
  ua-converter/ua_convert.py
Labels: enhancement
