Repository fake-useragent/fake-useragent, pull requests merged in 2024-03, with the labels that each got.

#290 Useragent list update
  README.md
  pyproject.toml
  src/fake_useragent/data/browsers.json
  src/fake_useragent/fake.py
  tests/test_fake.py
Labels: enhancement

#296 Create an auto merge dependabot workflow
  .github/workflows/dependabot_auto_merge.yml
Labels: enhancement, dependencies

#308 Removed trailing spaces in user agent strings.
  src/fake_useragent/data/browsers.json
Labels: bug
